"""archiviazione cliente: flag archiviato e data

Revision ID: 1dc54a77ecb4
Revises: 522d460a5485
Create Date: 2026-08-08 03:09:23.414525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc54a77ecb4'
down_revision = '522d460a5485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archiviato', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('archiviato_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clienti_archiviato'), ['archiviato'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clienti_archiviato'))
        batch_op.drop_column('archiviato_at')
        batch_op.drop_column('archiviato')

    # ### end Alembic commands ###
