"""rimuove il campo operatore dalla pratica

Revision ID: 2ce5d7e5739f
Revises: 1dc54a77ecb4
Create Date: 2026-08-08 04:06:16.423439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce5d7e5739f'
down_revision = '1dc54a77ecb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.drop_column('operatore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operatore', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
