"""schema iniziale con Pratica, Veicolo ed estensioni Cliente

Revision ID: 35a972207853
Revises: 
Create Date: 2026-07-28 18:08:11.286842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a972207853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('cognome', sa.String(length=80), nullable=False),
    sa.Column('indirizzo', sa.String(length=200), nullable=True),
    sa.Column('citta', sa.String(length=80), nullable=True),
    sa.Column('cap', sa.String(length=10), nullable=True),
    sa.Column('provincia', sa.String(length=4), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('cellulare', sa.String(length=40), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('data_nascita', sa.Date(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=40), nullable=True),
    sa.Column('numero_documento', sa.String(length=40), nullable=True),
    sa.Column('professione', sa.String(length=80), nullable=True),
    sa.Column('stato_civile', sa.String(length=40), nullable=True),
    sa.Column('convivenza', sa.Boolean(), nullable=True),
    sa.Column('num_figli', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clienti_codice_fiscale'), ['codice_fiscale'], unique=True)

    op.create_table('compagnie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('documenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('stored_name', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('stadio', sa.String(length=20), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=True),
    sa.Column('valore_stimato', sa.Float(), nullable=True),
    sa.Column('prossima_azione', sa.String(length=200), nullable=True),
    sa.Column('data_prossima_azione', sa.Date(), nullable=True),
    sa.Column('stadio_updated_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veicoli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('targa', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modello', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veicoli', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veicoli_targa'), ['targa'], unique=True)

    op.create_table('preventivi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('compagnia_id', sa.Integer(), nullable=True),
    sa.Column('oggetto', sa.String(length=200), nullable=True),
    sa.Column('premio_proposto', sa.Float(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('data_invio', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['compagnia_id'], ['compagnie.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('contratti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('preventivo_id', sa.Integer(), nullable=True),
    sa.Column('compagnia_id', sa.Integer(), nullable=True),
    sa.Column('numero_polizza', sa.String(length=40), nullable=False),
    sa.Column('ramo', sa.String(length=80), nullable=True),
    sa.Column('premio', sa.Float(), nullable=True),
    sa.Column('data_emissione', sa.Date(), nullable=True),
    sa.Column('data_scadenza', sa.Date(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['compagnia_id'], ['compagnie.id'], ),
    sa.ForeignKeyConstraint(['preventivo_id'], ['preventivi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incassi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('contratto_id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=True),
    sa.Column('importo', sa.Float(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('data_incasso', sa.Date(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['contratto_id'], ['contratti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sinistri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('contratto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=True),
    sa.Column('data_apertura', sa.Date(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('importo_stimato', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['contratto_id'], ['contratti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('pratiche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_identificativo', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('contratto_id', sa.Integer(), nullable=True),
    sa.Column('sinistro_id', sa.Integer(), nullable=True),
    sa.Column('stato', sa.String(length=30), nullable=False),
    sa.Column('priorita', sa.String(length=20), nullable=False),
    sa.Column('tipologia', sa.String(length=40), nullable=False),
    sa.Column('operatore', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_apertura', sa.DateTime(), nullable=True),
    sa.Column('data_ultimo_aggiornamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['contratto_id'], ['contratti.id'], ),
    sa.ForeignKeyConstraint(['sinistro_id'], ['sinistri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pratiche_numero_identificativo'), ['numero_identificativo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pratiche_numero_identificativo'))

    op.drop_table('pratiche')
    op.drop_table('sinistri')
    op.drop_table('incassi')
    op.drop_table('contratti')
    op.drop_table('preventivi')
    with op.batch_alter_table('veicoli', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veicoli_targa'))

    op.drop_table('veicoli')
    op.drop_table('lead')
    op.drop_table('documenti')
    op.drop_table('compagnie')
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clienti_codice_fiscale'))

    op.drop_table('clienti')
    # ### end Alembic commands ###
