"""fase A2: preventivo_id su pratiche, pratica_id su documenti, tabelle appuntamenti/comunicazioni/impostazioni_agenzia

Revision ID: 361e808ad3be
Revises: efa5719f8981
Create Date: 2026-07-30 11:39:20.167148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361e808ad3be'
down_revision = 'efa5719f8981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impostazioni_agenzia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ragione_sociale', sa.String(length=200), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('finestra1_inizio', sa.Time(), nullable=True),
    sa.Column('finestra1_fine', sa.Time(), nullable=True),
    sa.Column('finestra2_inizio', sa.Time(), nullable=True),
    sa.Column('finestra2_fine', sa.Time(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appuntamenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pratica_id', sa.Integer(), nullable=True),
    sa.Column('data_ora', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('esito', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['pratica_id'], ['pratiche.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunicazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pratica_id', sa.Integer(), nullable=True),
    sa.Column('canale', sa.String(length=20), nullable=False),
    sa.Column('destinatario', sa.String(length=200), nullable=True),
    sa.Column('testo', sa.Text(), nullable=True),
    sa.Column('data_invio', sa.DateTime(), nullable=True),
    sa.Column('esito', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['pratica_id'], ['pratiche.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pratica_id', sa.Integer(), nullable=True))
        # Nome esplicito del constraint: su SQLite create_foreign_key(None, ...)
        # fallisce con "Constraint must have a name".
        batch_op.create_foreign_key('fk_documenti_pratica_id_pratiche',
                                    'pratiche', ['pratica_id'], ['id'])

    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preventivo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pratiche_preventivo_id_preventivi',
                                    'preventivi', ['preventivo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pratiche_preventivo_id_preventivi',
                                 type_='foreignkey')
        batch_op.drop_column('preventivo_id')

    with op.batch_alter_table('documenti', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documenti_pratica_id_pratiche',
                                 type_='foreignkey')
        batch_op.drop_column('pratica_id')

    op.drop_table('comunicazioni')
    op.drop_table('appuntamenti')
    op.drop_table('impostazioni_agenzia')
    # ### end Alembic commands ###
