"""motivazione libera del motivo perdita sulla pratica

Aggiunge `pratiche.motivo_perdita_dettaglio`: il testo che l'operatore scrive
quando sceglie "altro" fra i motivi di perdita, dove l'elenco fisso non basta.

Colonna nuova e nullable, senza backfill: le pratiche gia' perse non hanno una
motivazione libera da recuperare, e il campo resta vuoto per tutti i motivi
diversi da "altro".

Revision ID: 7026369d95aa
Revises: 2ce5d7e5739f
Create Date: 2026-08-08 19:28:23.373847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7026369d95aa'
down_revision = '2ce5d7e5739f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_perdita_dettaglio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.drop_column('motivo_perdita_dettaglio')

    # ### end Alembic commands ###
