"""aggiunge lead_id a pratiche e veicolo_id a preventivi

Revision ID: efa5719f8981
Revises: 35a972207853
Create Date: 2026-07-29 17:13:35.596120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa5719f8981'
down_revision = '35a972207853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pratiche_lead_id_lead', 'lead', ['lead_id'], ['id'])

    with op.batch_alter_table('preventivi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veicolo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_preventivi_veicolo_id_veicoli', 'veicoli', ['veicolo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preventivi', schema=None) as batch_op:
        batch_op.drop_constraint('fk_preventivi_veicolo_id_veicoli', type_='foreignkey')
        batch_op.drop_column('veicolo_id')

    with op.batch_alter_table('pratiche', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pratiche_lead_id_lead', type_='foreignkey')
        batch_op.drop_column('lead_id')

    # ### end Alembic commands ###
